name: Workflow
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        working-directory: ./lab3
        run: pip install -r requirements.txt
      - name: Run tests
        working-directory: ./lab3
        run: export PYTHONPATH=$(pwd) && python test.py

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            registry: docker.dmitriy.space
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build image
        working-directory: ./lab3
        run: docker build -t docker.dmitriy.space/kabachki .

      - name: Docker push
        working-directory: ./lab3
        run: docker push docker.dmitriy.space/kabachki
